
backend:
  name: github
  repo: "brunoydev/my-blog"
  branch: "main"

media_folder: "public/postImages"
public_folder: "/postImages"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Pinned", name: "pinned", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

